// See https://aka.ms/new-console-template for more information
using Microsoft.Data.Sqlite;
using MT5toMTScript;
using System.Diagnostics;
using System.Text.Json;

Console.WriteLine("Convert MT5 database to MT8 format:");
string dbPath;
while (true)
{
    Console.WriteLine("Please enter file patH:");
    dbPath = Console.ReadLine()!.Trim().Trim('"');
    if (string.IsNullOrWhiteSpace(dbPath))
    {
        Console.WriteLine("Blank. Try again.");
        continue;
    }
    if (File.Exists(dbPath)) break;
    Console.WriteLine($"File '{dbPath}' doesn't exist, try again.");
}
Console.WriteLine("Okay nice, got it, what are we calling this new file?");
string fileName = Console.ReadLine()!.Trim();
if (!fileName.EndsWith(".mt")) fileName = fileName + ".mt";
Console.WriteLine("okay thanks...");
string outPath = $"C:\\Users\\Cornelius\\Desktop\\foodtrack\\MTScripts\\{fileName}";
Console.WriteLine($"Expoering to this:");
Console.WriteLine(outPath);
Console.WriteLine("You sure about that?");
Console.ReadLine();
using StreamWriter writer = new(outPath, false, System.Text.Encoding.UTF8);
var jsonOptions = new JsonSerializerOptions { WriteIndented = true };

string connString = $"Data Source={dbPath};Mode=ReadOnly;";
using var conn = new SqliteConnection(connString);
conn.Open();
using var cmd = new SqliteCommand("SELECT name FROM sqlite_master WHERE type='table';", conn);

Console.WriteLine("Connection established, printing all tables:");

using var reader = cmd.ExecuteReader();
while (reader.Read())
{
    Console.WriteLine(reader.GetString(0));
}

Console.WriteLine($"\nOkay let's do them. Press any key to continue :)");
Console.ReadLine();

Console.Write($"Constructing MetaData, sign here please: ");
string author = Console.ReadLine()!.Trim();
if (string.IsNullOrWhiteSpace(author))
{
    Console.WriteLine("Don't be shy!");
    author = Console.ReadLine()!.Trim();
}
ScriptMetaData meta = new("v0", fileName[..3], author, DateTime.Now);
Console.WriteLine($"MetaData will look like this:\n{meta.PrintInfo()}\nPress any key to start writing...");

// Do this in the exact order given. Under no circumstances put goal.activate before goal.add. Under no circumstances put Task.Set before Task.Add

Console.ReadLine();
string meth = JsonSerializer.Serialize(meta, jsonOptions);
writer.WriteLine("################################");
writer.WriteLine("Generated by MT5->.mt converter.");
writer.WriteLine("################################");
writer.WriteLine();
writer.WriteLine("ScriptMetadata");
writer.WriteLine(meth);

writer.WriteLine();
writer.WriteLine("// -- Diary Entries: --" + new string('-', 50) + " //");
writer.WriteLine();
DiaryConverter diary = new();
int diaryCount = diary.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {diaryCount} of diary entries");

writer.WriteLine();
writer.WriteLine("// -- Food Entries: ---" + new string('-', 50) + " //");
writer.WriteLine();
FoodConverter food = new();
int foodCount = food.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {foodCount} foor entries");

writer.WriteLine();
writer.WriteLine("// -- Goals: ----------" + new string('-', 50) + " //");
writer.WriteLine();
GoalConverter goal = new();
int goalcount = goal.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted like {goalcount} goals or something man...");

writer.WriteLine();
writer.WriteLine("// -- GoalActivations: " + new string('-', 50) + " //");
writer.WriteLine();
GoalActivateConverter gac = new();
int gacount = gac.Convers(conn, writer, jsonOptions);
Console.WriteLine($"Converted {gacount} I think I hope they work.");

writer.WriteLine();
writer.WriteLine("// -- Presets: --------" + new string('-', 50) + " //");
writer.WriteLine();
PresetConverter preset = new();
int presetCount = preset.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {presetCount} presets.");

writer.WriteLine();
writer.WriteLine("// -- AddTasks: -------" + new string('-', 50) + " //");
writer.WriteLine();
TaskConverter task = new();
int taskcount = task.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {taskcount} tasks.");

writer.WriteLine();
writer.WriteLine("// -- SetTasks: -------" + new string('-', 50) + " //");
writer.WriteLine();
SetTaskConverter stc = new();
int tasksetcount = stc.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Generated {tasksetcount} taskset statements");

writer.WriteLine();
writer.WriteLine("// -- Cheat days: -----" + new string('-', 50) + " //");
writer.WriteLine();
CheatConverter cheat = new();
int cheated = cheat.convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {cheated} cheadays");

writer.WriteLine();
writer.WriteLine("// -- Weight Entries:--" + new string('-', 50) + " //");
writer.WriteLine();
WeightConverter weight = new();
int weights = weight.Convert(conn, writer, jsonOptions);
Console.WriteLine($"Converted {weights} weight entries");


Process.Start(new ProcessStartInfo
{
    FileName = Path.GetDirectoryName(outPath),
    UseShellExecute = true
});

Process.Start(new ProcessStartInfo
{
    FileName = outPath,
    UseShellExecute = true
});